#let's set some boundaries, due to raspbian nowadays requiring a manual setup on first boot, this playbook assumes a user has already been created, it assumes said user is in the sudo group and that "%sudo ALL=(ALL) NOPASSWD:ALL" is set in the sudoers file
#SSH is obviously mandatory to deploy anything to the pi
#tailscale will also need to be manually logged into because I do not fancy adding api keys to this file
#unless variable -k is used at deployment a ssh key is required in the pi (eg: 'mkdir ~/.ssh && curl -o ~/.ssh/authorized_keys https://github.com/nlmln.keys')
- name: Deploy Pi with bowling control software
  hosts: all
  vars:
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
  become: true

  tasks:

  #TODO: switch away from using root to actually using user relay, startup.py currently depends on accessing /dev/mem
  - name: Add the group 'relay'
    group:
      name: relay
      state: present

  - name: Add the user 'relay'
    ansible.builtin.user:
      name: relay
      groups: relay
      shell: /sbin/nologin
      append: yes
    become: yes

  - name: Upgrade all apt packages
    apt:
      force_apt_get: yes
      upgrade: dist
    become: yes

  - name: Install python and git, dependencies for our software and apt-transport-https dependency for tailscale
    apt:
      name:
        - curl
        - python3-full
        - python3-flask
        - python3-rpi.gpio
        - git
        - apt-transport-https
      state: present
      update_cache: true

  #TODO: deploy tailscale with API keys instead of manually, this will probably happen in the form of a second private ansible file that deploys both tailscale and debug wpa_supplicant config
  #TODO: this sucks, find a better way to add repository or install tailscale in a different way, using /debian/ instead of raspbian because there's no raspbian bookworm release
  - name: Download tailscale-archive-keyring.gpg to add tailscale repository
    get_url:
      url: 'https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.noarmor.gpg'
      dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
      mode: 0644
      group: root
      owner: root
    become: yes

  - name: Download tailscale.list to add tailscale repository
    get_url:
      url: 'https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.tailscale-keyring.list'
      dest: /etc/apt/sources.list.d/tailscale.list
      mode: 0644
      group: root
      owner: root
    become: yes
       
  - name: Update repositories and cache to index new packages from third party repository
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600
    become: yes

  - name: Install utility software
    apt:
        name:
          - vim
          - tailscale
        state: present
        update_cache: true

  - name: Enable IP forwarding for tailscale
    ansible.posix.sysctl:
      name: '{{ item.key }}'
      value: '{{ item.value }}'
      sysctl_set: true
    with_dict: '{{ sysctl_config }}'

  - name: Create a Directory /opt/startup
    file:
      path: /opt/startup
      state: directory
      mode: 0755
      owner: relay
      group: relay
    become: yes

  - name: Download startup script into /opt/startup
    get_url:
      #TEMP: file in sasaa.nl needs to be edited
      url: https://nlmln.github.io/startup.py
      #url: https://www.sasaa.nl/.raspi/startup.py
      dest: /opt/startup/startup.py
      mode: 0755
      group: relay
      owner: relay
 
  # we had issues with this in the past, at worst this does nothing, at best this fixes a potential issue where the file is not executable
  - name: make sure that startup.py is in unix format
    shell: 'dos2unix /opt/startup/startup.py'
    become: yes

  - name: Create a Directory /opt/startup/templates
    file:
      path: /opt/startup/templates
      state: directory
      mode: 0755
      owner: relay
      group: relay
    become: yes

  #TODO: distribute webui as a tar file to ease future updates
  - name: Download bowling.html in /opt/startup/templates
    get_url:
      url: https://www.sasaa.nl/.raspi/bowling.html
      dest: /opt/startup/templates/bowling.html
      mode: 0644
      group: relay
      owner: relay

  - name: Download timers.html in /opt/startup/templates
    get_url:
      url: https://www.sasaa.nl/.raspi/timers.html
      dest: /opt/startup/templates/timers.html
      mode: 0644
      group: relay
      owner: relay

  #TODO: if using /dev/mem is necessary, edit relay.service to run as User=relay and Group=root, if not edit to User=relay and Group=relay
  - name: Download the relay.service systemd service
    get_url:
      #TEMP: file in sasaa.nl needs to be edited
      url: https://nlmln.github.io/relay.service
      #url: https://www.sasaa.nl/.raspi/relay.service
      dest: /etc/systemd/system/relay.service
      mode: 0755
      group: root
      owner: root
    become: yes

  - name: Enable and start the relay service
    systemd: state=started name=relay daemon_reload=yes

  - name: Set hostname relay for DNS discovery, making pi reachable at http://relay
    ansible.builtin.hostname:
      name: relay

  - name: Replace old hostname with new one in the hosts file
    ansible.builtin.replace:
      path: /etc/hosts
      regexp: 'raspberrypi'
      replace: 'relay'
    become: yes

#TODO: deploy debug wifi configuration
  - name: Turn on WLAN interface
    shell: 'rfkill unblock wlan'
    become: yes


#this should be kept as the last thing in the playbook because in most cases it will cause ansible to disconnect quickly after being applied
  - name: Set static IPv4 IP via NetworkManager
    nmcli:
      type: ethernet
      conn_name: Wired connection 1
      ip4: 10.10.115.2/24
      gw4: 10.10.115.250
      dns4: 
      - 62.179.104.196
      - 213.46.228.196
      state: present
    become: yes

